//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussion()
        {
            this.Fora = new HashSet<Forum>();
            this.Participants = new HashSet<Participant>();
            this.Polls = new HashSet<Poll>();
        }
    
        public int Id { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public string ClientName { get; set; }
        public string ClientEmail { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime DeletionDateTime { get; set; }
        public string ModeratorEmail { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PauseDateTime { get; set; }
    
        public virtual Moderator Moderator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forum> Fora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poll> Polls { get; set; }
    }
}
