//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumReply
    {
        public int Id { get; set; }
        public string Reply { get; set; }
        public int ForumCommentID { get; set; }
        public int ParticipantID { get; set; }
        public System.DateTime PostedOn { get; set; }
    
        public virtual ForumComment ForumComment { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
