//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumComment()
        {
            this.ForumReplies = new HashSet<ForumReply>();
        }
    
        public int Id { get; set; }
        public string Comment { get; set; }
        public int ForumID { get; set; }
        public int ParticipantID { get; set; }
        public System.DateTime PostedOn { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual Participant Participant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumReply> ForumReplies { get; set; }

        public ForumReply ForumReply
        {
            get => default;
            set
            {
            }
        }
    }
}
