//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollVote
    {
        public int Id { get; set; }
        public int ParticipantID { get; set; }
        public int PollOptionID { get; set; }
        public int PollID { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Poll Poll { get; set; }
        public virtual PollOption PollOption { get; set; }
    }
}
